# Generated by Django 3.0.4 on 2020-03-23 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_count', models.IntegerField()),
                ('right_hand_side', models.IntegerField()),
                ('equality_type', models.CharField(choices=[('=', 'Equal'), ('<=', 'Less Than Equal'), ('>=', 'Greater Than Equal')], default='=', max_length=2)),
                ('coefficients', models.CharField(max_length=1024)),
                ('is_objective', models.BooleanField()),
                ('is_constraint', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Equation',
                'verbose_name_plural': 'Equations',
            },
        ),
        migrations.CreateModel(
            name='LpProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('constrains', models.ManyToManyField(blank=True, related_name='lps', to='simplex.Equation')),
                ('objective', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='simplex.Equation')),
            ],
            options={
                'verbose_name': 'LpProblem',
                'verbose_name_plural': 'LpProblems',
            },
        ),
    ]
